In [1]:
import numpy as np

In [2]:
n=int(input("enter the value of n"))

umbr=np.random.uniform(0,1,size=(1,n))


beta=np.random.randint(0,5,size=(1,n))



kr=np.random.randint(-5,5,size=(1,n))


maxcount=np.random.randint(50,100,size=(1,n))

a=np.random.uniform(1,16,size=(4,n))
print(a.T)


enter the value of n6
[[ 7.37036667 10.67476784 10.68850025  8.21808881]
 [ 4.35740356 15.16641024  4.22490426  7.72534637]
 [ 6.69193189 12.00827374  1.12713077  8.9298673 ]
 [ 3.51389782 10.37371715  2.26654981  3.42780131]
 [ 3.29734708  7.4224616   8.07247889  7.87773412]
 [12.93884329  5.47234504 11.19071697 13.2897298 ]]


In [3]:
motherpopulation = dict()
numpop = int(input("Enter the number of population "))
for i in range(1,(numpop//2)+1):
    key = 'FG1-'+str(i)
    print(key)
    print(' ')
    ratio = np.random.randint(5,11) 
    print(ratio)
    value = np.random.uniform(a.T)
    print(value)
    motherpopulation[key] = [value, ratio]
    print(' ')
    

fatherpopulation = dict()
for i in range(1,(numpop//2)+1):
    key = 'MG1-'+str(i)
    print(key)
    print(' ')
    ratio = np.random.randint(5,11) 
    print(ratio)
    value = np.random.uniform(a.T)
    print(value)
    fatherpopulation[key] = [value, ratio]
    print(' ')




Enter the number of population 4
FG1-1
 
5
[[ 5.24916859  4.26767481  6.74226082  4.77860424]
 [ 3.12845908 10.50303236  3.42260439  3.29635837]
 [ 2.7773185   3.81341677  1.06360497  2.25391617]
 [ 2.74941521  1.39762496  1.79617401  1.09513371]
 [ 2.10510909  4.81226722  3.28497726  2.09793034]
 [10.65571     2.88111703 11.13324973  1.2916219 ]]
 
FG1-2
 
3
[[ 1.51097732  8.42336616  2.78901219  4.82034248]
 [ 3.53025944 14.19671708  2.29769801  5.33459109]
 [ 5.79917047  7.48584167  1.05901472  6.68105326]
 [ 2.84507765  2.07113106  2.14542363  2.22861399]
 [ 2.82405465  6.26457513  3.28492158  6.88225865]
 [ 4.12973139  3.25481812  5.6550897   1.52560255]]
 
MG1-1
 
1
[[ 2.47435752  9.2671578  10.08117379  2.37828391]
 [ 2.46237643 11.40563061  1.17417909  6.03192387]
 [ 4.81313424  9.43385406  1.03288024  2.41806988]
 [ 3.44621871  5.49092892  1.52200106  3.01361005]
 [ 1.35527069  7.41971428  4.78181578  7.78004807]
 [12.29123782  3.21431346  7.59550941  5.7073864 ]]
 
MG1-2
 
3


In [6]:
print(fatherpopulation, motherpopulation, sep='\n')
generation=1
def assignbaby():
    # This method picks a gender for the baby randomly
    let = [ 'M', 'F']     
    import random
    pos = random.randint(0,1)
    letter = let[pos]
    return letter

def avg_fitness_per_gen(fatherpopulation, motherpopulation):
  # This method calculates the average of the fitness ratio 
  # for each generation in the current population
  generation_count = dict()
  for key in fatherpopulation.keys():
    hyphen_ind = key.find('-')
    gen_int = int(key[2:hyphen_ind])
    gen_list = generation_count.get(gen_int, [])
    gen_list.append(fatherpopulation[key][1])
    generation_count[gen_int] = gen_list

  for key in motherpopulation.keys():
    hyphen_ind = key.find('-')
    gen_int = int(key[2:hyphen_ind])
    gen_list = generation_count.get(gen_int, [])
    gen_list.append(motherpopulation[key][1])
    generation_count[gen_int] = gen_list

  gen_avg_fitness = dict()
  for key in generation_count.keys():
    avg = sum(generation_count[key]) / len(generation_count[key])
    gen_avg_fitness[key] = gen_avg_fitness.get(key, 0.0) + avg
  return gen_avg_fitness

def create_baby(father, mother, number, generation):
    # If both father and mother are unfit, not creating a baby
    if father[1] < 6 and mother[1] < 6: return ('', '') 
    # choosing a number at random to represent the choice of rows from mother
    # and father matrices (if a bit is 0 that index is filled with mother's row
    # else filled with father's row at that index) to get the baby matrix
    r=((2**n)-2)
    comb = np.random.randint(1,r,size=1)[0]
    # to ensure we get 4 bits (removing zfill strips the leading zeros if any)
    bin_comb = bin(comb)[2:].zfill(n)
    #debug print, can be removed
    print("bin_comb: ", bin_comb)
    baby = []
    for i in range(len(bin_comb)):
        if bin_comb[i] == '0': baby.append(mother[0][i])
        else: baby.append(father[0][i])
    baby = np.asarray(baby)
    baby_fr =np.random.randint(5,11)
    baby_gender=assignbaby()
    key = baby_gender+'G' + str(generation + 1) + '-' + str(number)
    if baby_gender == 'F':
        motherpopulation[key] = [baby, baby_fr]
    else:
        fatherpopulation[key] = [baby, baby_fr]
    return (baby_gender, key)

for i in range(1, (numpop//2)+1):
    print("generating baby ", i)
    father_key = 'MG1-'+str(i)
    mother_key = 'FG1-'+str(i)
    baby_gender, baby_title = create_baby(fatherpopulation[father_key], 
                                          motherpopulation[mother_key], 
                                          i, generation)
    if baby_title != '':
        print(baby_title)
    else:
        print("This couple cannot give birth to a fit baby")
    if baby_gender == 'F':
        print(motherpopulation[baby_title])
    elif baby_gender == 'M':
        print(fatherpopulation[baby_title])
generation += 1 # Manual Gen-2 creation
print(avg_fitness_per_gen(fatherpopulation, motherpopulation))

{'MG1-1': [array([[ 2.47435752,  9.2671578 , 10.08117379,  2.37828391],
       [ 2.46237643, 11.40563061,  1.17417909,  6.03192387],
       [ 4.81313424,  9.43385406,  1.03288024,  2.41806988],
       [ 3.44621871,  5.49092892,  1.52200106,  3.01361005],
       [ 1.35527069,  7.41971428,  4.78181578,  7.78004807],
       [12.29123782,  3.21431346,  7.59550941,  5.7073864 ]]), 1], 'MG1-2': [array([[ 2.10917185,  6.31133204, 10.62446586,  4.82874736],
       [ 3.05447769,  1.20997863,  3.48760344,  5.58923241],
       [ 5.84135411,  3.1811651 ,  1.07753837,  6.71036145],
       [ 2.08067879,  3.25503008,  1.35940068,  2.03486583],
       [ 2.6602002 ,  4.90688925,  2.14070301,  4.21989345],
       [ 5.45301279,  2.74872922,  2.4124174 , 12.63660404]]), 3]}
{'FG1-1': [array([[ 5.24916859,  4.26767481,  6.74226082,  4.77860424],
       [ 3.12845908, 10.50303236,  3.42260439,  3.29635837],
       [ 2.7773185 ,  3.81341677,  1.06360497,  2.25391617],
       [ 2.74941521,  1.39762496,  1.7961

In [ ]:
def create_pop_matrix():
  # This method creates a list of all the titles currently
  # "alive" in the father / mother population
  # This is needed to update the population after every
  # death / birth cycle later in this document
  pop_matrix = []
  for key in fatherpopulation.keys():
    pop_matrix.append(key)
  for key in motherpopulation.keys():
    pop_matrix.append(key)
  return pop_matrix
pop_matrix = create_pop_matrix()
print(pop_matrix)

def delete_min(pop_matrix):
  # This method is used to simulate the 
  # "death of the least fit" in the population.
  # Simply picking minimum in the population
  min_fr = 11
  min_title = ""

  for title in pop_matrix:
    if title[0]=='M' and fatherpopulation[title][1] < min_fr:
      min_fr = fatherpopulation[title][1]
      min_title = title
    if title[0]=='F' and motherpopulation[title][1] < min_fr:
      min_fr = motherpopulation[title][1]
      min_title = title

  if min_title[0]=='M':
    del fatherpopulation[min_title]
  else:
    del motherpopulation[min_title]
  
  return min_title

def createnextgen(pop_matrix, death_ratio, generation):
  # This method simulates one cycle of the death / birth
  # cycle by killing floor(population * death_ratio / 100)
  # titles and replacing them with the next generation 
  import random
  #death_ratio = int(input("Enter the death ratio (0 - 30 %): "))
  for baby_no in range(len(pop_matrix)*death_ratio//100):
    deleted_title = delete_min(pop_matrix)
    print("Death of ->", deleted_title)
    father_title = str(random.choice(list(fatherpopulation.keys())))
    mother_title = str(random.choice(list(motherpopulation.keys())))
    baby_gender, baby_title = create_baby(fatherpopulation[father_title], 
                                          motherpopulation[mother_title], 
                                          baby_no+1, generation)
    pop_matrix = create_pop_matrix()
    #print(motherpopulation,fatherpopulation)
    #print(pop_matrix)
  return pop_matrix


In [ ]:
gc = int(input("Enter No. of Generations: "))
generation = 2
dr=int(input("Enter the death ratio (0 - 30 %): "))
for _ in range(gc):
  pop_matrix = createnextgen(pop_matrix, dr, generation)
  generation += 1
  print(pop_matrix)
  print(avg_fitness_per_gen(fatherpopulation, motherpopulation))

In [ ]:
print(pop_matrix)

In [ ]:
import matplotlib.pyplot as plt
plt.hist(pop_matrix)
plt.show()

NameError: name 'FG1' is not defined

In [7]:
print(motherpopulation)

{'FG1-1': [array([[ 5.24916859,  4.26767481,  6.74226082,  4.77860424],
       [ 3.12845908, 10.50303236,  3.42260439,  3.29635837],
       [ 2.7773185 ,  3.81341677,  1.06360497,  2.25391617],
       [ 2.74941521,  1.39762496,  1.79617401,  1.09513371],
       [ 2.10510909,  4.81226722,  3.28497726,  2.09793034],
       [10.65571   ,  2.88111703, 11.13324973,  1.2916219 ]]), 5], 'FG1-2': [array([[ 1.51097732,  8.42336616,  2.78901219,  4.82034248],
       [ 3.53025944, 14.19671708,  2.29769801,  5.33459109],
       [ 5.79917047,  7.48584167,  1.05901472,  6.68105326],
       [ 2.84507765,  2.07113106,  2.14542363,  2.22861399],
       [ 2.82405465,  6.26457513,  3.28492158,  6.88225865],
       [ 4.12973139,  3.25481812,  5.6550897 ,  1.52560255]]), 3]}


In [8]:
print(fatherpopulation)

{'MG1-1': [array([[ 2.47435752,  9.2671578 , 10.08117379,  2.37828391],
       [ 2.46237643, 11.40563061,  1.17417909,  6.03192387],
       [ 4.81313424,  9.43385406,  1.03288024,  2.41806988],
       [ 3.44621871,  5.49092892,  1.52200106,  3.01361005],
       [ 1.35527069,  7.41971428,  4.78181578,  7.78004807],
       [12.29123782,  3.21431346,  7.59550941,  5.7073864 ]]), 1], 'MG1-2': [array([[ 2.10917185,  6.31133204, 10.62446586,  4.82874736],
       [ 3.05447769,  1.20997863,  3.48760344,  5.58923241],
       [ 5.84135411,  3.1811651 ,  1.07753837,  6.71036145],
       [ 2.08067879,  3.25503008,  1.35940068,  2.03486583],
       [ 2.6602002 ,  4.90688925,  2.14070301,  4.21989345],
       [ 5.45301279,  2.74872922,  2.4124174 , 12.63660404]]), 3]}
